[config] Revert r38804. Apparently, it causes PARROT_HAS_GETTEXT to be falsely defined on OSX, resulting in build errors:
/Users/jimk/work/parrot/include/parrot/parrot.h:239:23: error: libintl.h: No such file or directory

Revert it for now, until a better solution can be found.
masak++ and kid51++ for reporting and bisecting.