[perl #30874] [PATCH] src/packdump.c
Currently pdump doesn't build because of a booboo in src/packdump.c -
this is for example what gcc thinks of it:

src/packdump.c: In function `PackFile_Constant_dump':
src/packdump.c:123: error: dereferencing pointer to incomplete type

Courtesy of Jarkko Hietaniemi <jhi@iki.fi>